# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"1\n\rConfigRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\"2\n\x0e\x43onfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x10InferenceRequest\x12\x12\n\ninput_text\x18\x01 \x01(\t\"7\n\x11InferenceResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32\xa8\x01\n\x10InferenceService\x12G\n\x0e\x43onfigureModel\x12\x18.inference.ConfigRequest\x1a\x19.inference.ConfigResponse\"\x00\x12K\n\x0cRunInference\x12\x1b.inference.InferenceRequest\x1a\x1c.inference.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGREQUEST']._serialized_start=30
  _globals['_CONFIGREQUEST']._serialized_end=79
  _globals['_CONFIGRESPONSE']._serialized_start=81
  _globals['_CONFIGRESPONSE']._serialized_end=131
  _globals['_INFERENCEREQUEST']._serialized_start=133
  _globals['_INFERENCEREQUEST']._serialized_end=171
  _globals['_INFERENCERESPONSE']._serialized_start=173
  _globals['_INFERENCERESPONSE']._serialized_end=228
  _globals['_INFERENCESERVICE']._serialized_start=231
  _globals['_INFERENCESERVICE']._serialized_end=399
# @@protoc_insertion_point(module_scope)
