---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant
  namespace: platform
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:latest
        ports:
        - containerPort: 6333
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  namespace: platform
  labels:
    app: qdrant
spec:
  ports:
  - port: 6333
    targetPort: 6333
  selector:
    app: qdrant
  type: ClusterIP
